export const drawers = {
  rows: 10,
  cols: 12,
  drawers: [
    null,
    null,
    null,
    null,
    null,
    null,
    { boxNumber: null, project: "401952", completed: false },
    { boxNumber: null, project: "402915", completed: false },
    { boxNumber: null, project: "", completed: false },
    { boxNumber: null, project: "402885", completed: false },
    { boxNumber: null, project: "402868", completed: false },
    { boxNumber: null, project: "400949", completed: false },
    null,
    null,
    null,
    null,
    null,
    null,
    { boxNumber: null, project: "402357", completed: false },
    { boxNumber: null, project: "402729", completed: false },
    { boxNumber: null, project: "", completed: false },
    { boxNumber: null, project: "402540", completed: false },
    { boxNumber: null, project: "402068", completed: false },
    { boxNumber: null, project: "400415", completed: false },
    null,
    null,
    null,
    null,
    null,
    null,
    { boxNumber: null, project: "401577", completed: false },
    { boxNumber: null, project: "402158", completed: false },
    { boxNumber: null, project: "401885", completed: false },
    { boxNumber: null, project: "402294", completed: false },
    { boxNumber: null, project: "402525", completed: false },
    { boxNumber: null, project: "402261", completed: false },
    null,
    null,
    null,
    null,
    null,
    null,
    { boxNumber: null, project: "", completed: false },
    { boxNumber: null, project: "402547", completed: false },
    { boxNumber: null, project: "", completed: false },
    { boxNumber: null, project: "400654", completed: false },
    { boxNumber: null, project: "401975", completed: false },
    { boxNumber: null, project: "402907", completed: false },
    null,
    null,
    null,
    null,
    null,
    null,
    { boxNumber: null, project: "402809", completed: false },
    { boxNumber: null, project: "400182", completed: false },
    { boxNumber: null, project: "401835", completed: false },
    { boxNumber: null, project: "400952", completed: false },
    { boxNumber: null, project: "402905", completed: false },
    { boxNumber: null, project: "402293", completed: false },
    { boxNumber: null, project: "402743", completed: false },
    { boxNumber: null, project: "401655", completed: true },
    { boxNumber: null, project: "400881", completed: false },
    { boxNumber: null, project: "401950", completed: false },
    { boxNumber: null, project: "401567", completed: false },
    { boxNumber: null, project: "402379", completed: false },
    { boxNumber: null, project: "400892", completed: false },
    { boxNumber: null, project: "400951", completed: false },
    { boxNumber: null, project: "400706", completed: false },
    { boxNumber: null, project: "402512", completed: false },
    { boxNumber: null, project: "400981", completed: false },
    { boxNumber: null, project: "400416", completed: false },
    { boxNumber: null, project: "401220", completed: false },
    { boxNumber: null, project: "400975", completed: false },
    { boxNumber: null, project: "402831", completed: false },
    { boxNumber: null, project: "400087", completed: false },
    { boxNumber: null, project: "400802", completed: false },
    { boxNumber: null, project: "401249", completed: false },
    { boxNumber: null, project: "401957", completed: false },
    { boxNumber: null, project: "400623", completed: false },
    { boxNumber: null, project: "401914", completed: false },
    { boxNumber: null, project: "401578", completed: false },
    { boxNumber: null, project: "402903", completed: false },
    { boxNumber: null, project: "402084", completed: false },
    { boxNumber: null, project: "402546", completed: true },
    { boxNumber: null, project: "401248", completed: false },
    { boxNumber: null, project: "402849", completed: false },
    { boxNumber: null, project: "402759", completed: false },
    { boxNumber: null, project: "402472", completed: false },
    { boxNumber: null, project: "402180", completed: false },
    { boxNumber: null, project: "", completed: false },
    { boxNumber: null, project: "", completed: false },
    { boxNumber: null, project: "", completed: false },
    { boxNumber: null, project: "402295", completed: false },
    { boxNumber: null, project: "401603", completed: false },
    { boxNumber: null, project: "401534", completed: false },
    { boxNumber: null, project: "402392", completed: false },
    { boxNumber: null, project: "400294", completed: false },
    { boxNumber: null, project: "402917", completed: false },
    { boxNumber: null, project: "402896", completed: true },
    { boxNumber: null, project: "401582", completed: false },
    { boxNumber: null, project: "402152", completed: false },
    { boxNumber: null, project: "401852", completed: false },
    { boxNumber: null, project: "", completed: false },
    { boxNumber: null, project: "", completed: false },
    { boxNumber: null, project: "", completed: false },
    { boxNumber: null, project: "402371", completed: false },
    { boxNumber: null, project: "402676", completed: false },
    { boxNumber: null, project: "400000", completed: true },
    { boxNumber: null, project: "402155", completed: false },
    { boxNumber: null, project: "402411", completed: false },
    { boxNumber: null, project: "402069", completed: false },
    { boxNumber: null, project: "402102", completed: false },
    { boxNumber: null, project: "402337", completed: false },
    { boxNumber: null, project: "402487", completed: false },
    { boxNumber: null, project: "402825", completed: false },
    { boxNumber: null, project: "400972", completed: false },
    { boxNumber: null, project: "401418", completed: false },
    { boxNumber: null, project: "", completed: false },
    { boxNumber: null, project: "", completed: false },
  ],
};
